services:
  - type: web
    name: NEZUKO
    env: node
    branch: main
    repo: https://github.com/godzenitsu/Nezuko.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
      - key: MODE
        value: private
      - key: AUTO_STATUS_SEEN
        value: true
      - key: AUTO_READ
        value: true
      - key: AUTO_TYPING
        value: true
      - key: REJECT_CALL
        value: false
      - key: ALWAYS_ONLINE
        value: true
      - key: AUTO_BLOCK
        value: false
